### ISSUE TITLE
Make closing image modal easier

### ISSUE THREAD

**Issue by tlmader** [tlmader/patinaproject-issues#2]
**Is your feature request related to a problem? Please describe.**
Users have trouble figuring out how to close the image modal. This particularly affects iPhone users without a back button.

**Describe the solution you'd like**
Allow users to close the image modal using a swipe gesture.

**Additional context**
- https://patina-project.sleekplan.app/feedback/17568

**Comment by harurang** [comment]
https://user-images.githubusercontent.com/19256679/156902159-e98d0c0f-dd0f-42db-9728-38347a5c75d6.mp4
